server:
  port: 8081
  servlet:
    context-path: /oreillyapp
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: 
        - metrics
        - info
        - health
spring:
  profiles:
    active: development
  datasource:
    name: fullstackdb
    password: password
    url: jdbc:postgresql://localhost:5432/oreillyfullstack
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
---
spring:
  config:
    activate:
      on-profile: development
server:
  servlet:
    context-path: /oreillydevapp

---
spring:
  config:
    activate:
      on-profile: production
server:
  port: 8083
  servlet:
    context-path: /oreillyprodapp